human_languages = [
    "English",
    "E n g l i s h",
    "Spanish",
    "S p a n i s h",
    "Mandarin Chinese",
    "Hindi",
    "H i n d i",
    "Arabic",
    "A r a b i c",
    "Malayalam",
    "M a l a y a l a m",
    "Tamil",
    "T a m i l",
    "Punjabi",
    "P u n j a b i",
    "Gujarati",
    "G u j a r a t i",
    "French",
    "F r e n c h",
    "Kannada",
    "K a n n a d a",
    "Telugu",
    "T e l u g u",
    "Russian",
    "R u s s i a n",
    "German",
    "G e r m a n",
    "Japanese",
    "J a p a n e s e",
    "Portuguese",
    "P o r t u g u e s e",
    "Bengali",
    "B e n g a l i",
    "Urdu",
    "U r d u",
    "Indonesian",
    "Italian",
    "I t a l i a n",
    "Dutch",
    "D u t c h",
    "Turkish",
    "T u r k i s h",
    "Vietnamese",
    "V i e t n a m e s e",
    "Polish",
    "P o l i s h",
    "Ukrainian",
    "U k r a i n i a n",
    "Persian",
    "P e r s i a n",
    "Thai",
    "T h a i",
    "Korean",
    "K o r e a n",
    "Tagalog",
    "T a g a l o g",
    "Swahili",
    "S w a h i l i",
    "Yoruba",
    "Y o r u b a",
    "Igbo",
    "I g b o",
    "Hausa",
    "H a u s a",
    "Zulu",
    "Z u l u" "Swedish",
    "S w e d i s h",
    "Danish",
    "Norwegian",
    "N o r w e g i a n",
    "Finnish",
    "F i n n i s h",
    "Greek",
    "G r e e k",
    "Hebrew",
    "H e b r e w",
    "Czech",
    "C z e c h",
    "Hungarian",
    "H u n g a r i a n",
    "Romanian",
    "R o m a n i a n",
    "Bulgarian",
    "B u l g a r i a n",
    "Hmong",
    "H m o n g",
    "Lao",
    "L a o",
    "Khmer",
    "K h m e r" "Slovak",
    "S l o v a k",
    "Slovenian",
    "S l o v e n i a n",
    "Maltese",
    "M a l t e s e",
    "Latvian",
    "L a t v i a n",
    "Lithuanian",
    "L i t u a n i a n",
    "Estonian",
    "E s t o n i a n",
    "Albanian",
    "A l b a n i a n",
    "Serbian",
    "S e r b i a n",
    "Croatian",
    "C r o a t i a n",
    "Bosnian",
    "B o s n i a n",
    "Macedonian",
    "M a c e d o n i a n",
    "Montenegrin",
    "M o n t e n e g r i n",
    "Georgian",
    "G e o r g i a n",
    "Armenian",
    "A r m e n i a n",
    "Azerbaijani",
    "A z e r b a i j a n i",
    "Kazakh",
    "K a z a k h",
    "Turkmen",
    "T u r k m e n",
    "Uzbek",
    "U z b e k",
    "Tajik",
    "T a j i k",
    "Kyrgyz",
    "K y r g y z",
    "Tatar",
    "T a t a r",
    "Bashkir",
    "B a s h k i r",
    "Mongolian",
    "M o n g o l i a n",
    "Tibetan",
    "T i b e t a n",
    "Uighur",
    "U i g h u r",
    "Manchu",
    "M a n c h u",
    "Tuvan",
    "T u v a n",
    "Chuvash",
    "C h u v a s h",
    "Chechen",
    "C h e c h e n",
    "Ingush",
    "I n g u s h",
    "Avar",
    "A v a r",
    "Lezgian",
    "L e z g i a n",
    "Abkhaz",
    "A b k h a z",
    "Ossetian",
    "O s s e t i a n",
    "Komi",
    "K o m i",
    "Mari",
    "M a r i",
    "Moksha",
    "M o k s h a",
    "Udmurt",
    "U d m u r t",
    "Erzya",
    "E r z y a",
    "Komi-Permyak",
    "K o m i - P e r m y a k",
    "Komi-Zyrian",
    "K o m i - Z y r i a n",
]


def extract_languages(resume_text, nlp):
    doc = nlp(resume_text)

    extracted_languages = [
        lang
        for lang in human_languages
        if lang.lower() in "".join(resume_text.split()).lower()
    ]

    if len(extracted_languages) > 1:
        message = "Impressive! Your resume indicates proficiency in multiple languages. Highlighting diverse language skills can be a valuable asset."
    elif len(extracted_languages) == 1:
        message = "Your resume indicates proficiency in only one language. Consider adding more language skills to enhance your profile."
    else:
        message = "Your resume does not indicate any language skills. Consider adding language skills to enhance your profile."

    return {
        "languages": list(set(extracted_languages)),
        "message": message,
    }


# spaced_data = [
#     "E n g l i s h",
#     "S p a n i s h",
#     "M a n d a r i n C h i n e s e",
#     "H i n d i",
#     "A r a b i c",
#     "M a l a y a l a m",
#     "T a m i l",
#     "P u n j a b i",
#     "G u j a r a t i",
#     "F r e n c h",
#     "K a n n a d a",
#     "T e l u g u",
#     "R u s s i a n",
#     "G e r m a n",
#     "J a p a n e s e",
#     "P o r t u g u e s e",
#     "B e n g a l i",
#     "U r d u",
#     "I t a l i a n",
#     "D u t c h",
#     "T u r k i s h",
#     "V i e t n a m e s e",
#     "P o l i s h",
#     "U k r a i n i a n",
#     "P e r s i a n",
#     "T h a i",
#     "K o r e a n",
#     "T a g a l o g",
#     "S w a h i l i",
#     "Y o r u b a",
#     "I g b o",
#     "H a u s a",
#     "Z u l u",
#     "S w e d i s h",
#     "N o r w e g i a n",
#     "F i n n i s h",
#     "G r e e k",
#     "H e b r e w",
#     "C z e c h",
#     "H u n g a r i a n",
#     "R o m a n i a n",
#     "B u l g a r i a n",
#     "H m o n g",
#     "L a o",
#     "K h m e rSlovak",
#     "S l o v a k",
#     "S l o v e n i a n",
#     "M a l t e s e",
#     "L a t v i a n",
#     "L i t u a n i a n",
#     "E s t o n i a n",
#     "A l b a n i a n",
#     "S e r b i a n",
#     "C r o a t i a n",
#     "B o s n i a n",
#     "M a c e d o n i a n",
#     "M o n t e n e g r i n",
#     "G e o r g i a n",
#     "A r m e n i a n",
#     "A z e r b a i j a n i",
#     "K a z a k h",
#     "T u r k m e n",
#     "U z b e k",
#     "T a j i k",
#     "K y r g y z",
#     "T a t a r",
#     "B a s h k i r",
#     "M o n g o l i a n",
#     "T i b e t a n",
#     "U i g h u r",
#     "M a n c h u",
#     "T u v a n",
#     "C h u v a s h",
#     "C h e c h e n",
#     "I n g u s h",
#     "A v a r",
#     "L e z g i a n",
#     "A b k h a z",
#     "O s s e t i a n",
#     "K o m i",
#     "M a r i",
#     "M o k s h a",
#     "U d m u r t",
#     "E r z y a",
#     "K o m i - P e r m y a k",
#     "K o m i - Z y r i a n",
# ]
